timeout = 500 # 单位 ms
healthcheck = 5 # 健康检查间隔时间 单位 s
upstream = [
    "https://stackoverflow.com:443",
]

[backends]
[backends.8080]
host = ""
upstream = "upstream"
url = [
    "https://github.com:443"
]
backup = "https://github.com:443"